// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA98-xmDbUrzL8zYq-ilG2Z-frjyZgUPk0',
    appId: '1:897128199289:web:f7968012f51eb9a4cf10a8',
    messagingSenderId: '897128199289',
    projectId: 'split-buddy',
    authDomain: 'split-buddy.firebaseapp.com',
    storageBucket: 'split-buddy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtvVOWqJnvU7yKUrWxluKb3C9uX_kwUKU',
    appId: '1:897128199289:android:cea8e6b2f84459d2cf10a8',
    messagingSenderId: '897128199289',
    projectId: 'split-buddy',
    storageBucket: 'split-buddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe9BQUZgBZRphVjTi7GfEKjQicJ-iOaqc',
    appId: '1:897128199289:ios:d7bdf11b1a6a482ccf10a8',
    messagingSenderId: '897128199289',
    projectId: 'split-buddy',
    storageBucket: 'split-buddy.appspot.com',
    iosClientId: '897128199289-co6llmjhv0on38qm3lffrug4jceicn9d.apps.googleusercontent.com',
    iosBundleId: 'app.splitbuddy.splitbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe9BQUZgBZRphVjTi7GfEKjQicJ-iOaqc',
    appId: '1:897128199289:ios:d7bdf11b1a6a482ccf10a8',
    messagingSenderId: '897128199289',
    projectId: 'split-buddy',
    storageBucket: 'split-buddy.appspot.com',
    iosClientId: '897128199289-co6llmjhv0on38qm3lffrug4jceicn9d.apps.googleusercontent.com',
    iosBundleId: 'app.splitbuddy.splitbuddy',
  );
}
